name: ringcentral
description: RingCentral SDK for Dart language. It allows developers to invoke RingCentral Platform API.
version: 0.1.2
homepage: https://github.com/ringcentral/ringcentral-dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
